<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.064" timestamp="2023-11-15T20:03:31.249923" hostname="vagrant"><testcase classname="test_class.TestClass" name="test_one" time="0.001" /><testcase classname="test_class.TestClass" name="test_two" time="0.001"><failure message="AssertionError: assert False&#10; +  where False = hasattr('hello', 'check')">self = &lt;test_class.TestClass object at 0x7f8687174850&gt;

    def test_two(self):
        x = "hello"
&gt;       assert hasattr(x, "check")
E       AssertionError: assert False
E        +  where False = hasattr('hello', 'check')

test_class.py:8: AssertionError</failure></testcase><testcase classname="test_sample" name="test_answer" time="0.001" /><testcase classname="test_sysexit" name="test_mytest" time="0.001" /></testsuite></testsuites>